sudo: false

language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2

before_script:
    - travis_retry composer self-update

script:
    - composer phpunit_data_provider_yaml:test
    - vendor/bin/test-reporter --coverage-report=coverage.xml